// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLuYtCaUbXNdASbVsDf4Clit8H4NGMto',
    appId: '1:617451345231:android:c164d56da4985998d1613a',
    messagingSenderId: '617451345231',
    projectId: 'intelivita-task-881d6',
    storageBucket: 'intelivita-task-881d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhRvpQplmy2vUdEDWkAT92RMADC7XjXio',
    appId: '1:617451345231:ios:2fe0429a846e7799d1613a',
    messagingSenderId: '617451345231',
    projectId: 'intelivita-task-881d6',
    storageBucket: 'intelivita-task-881d6.firebasestorage.app',
    androidClientId: '617451345231-srhe3ter6tek08d6r2ndkaomptmkdbbj.apps.googleusercontent.com',
    iosClientId: '617451345231-o8adht4dcevs8nj9do8g4h987age6mrh.apps.googleusercontent.com',
    iosBundleId: 'com.intelivita.task',
  );

}